#include "../app-sdk/desktop_plugin.h"
#include <stdio.h>
#include <string.h>
typedef struct{DmTaskInfo tasks[DM_MAX_WINDOWS];int count,selected;DmWindow*chosen;} Manager;
static void tick(DmWindow*w,unsigned ms){(void)ms;Manager*m=w->state;m->count=dm_tasks(m->tasks,DM_MAX_WINDOWS);m->selected=-1;for(int i=0;i<m->count;i++)if(m->tasks[i].window==m->chosen)m->selected=i;}
static void open_manager(DmWindow*w,const char*a){(void)a;tick(w,0);}
static void draw(DmWindow*w){Manager*m=w->state;dm_text(w->x+20,w->y+65,dm_localize("Applicazioni | RAM tracciata per app","Apps | tracked RAM per app","Apps | RAM medida por app"),DM_COLOR(24,38,55,255));for(int i=0;i<m->count;i++){int y=w->y+85+i*28;dm_rect(w->x+20,y,w->w-40,27,i==m->selected?DM_COLOR(158,203,247,255):DM_COLOR(255,255,255,255));dm_text(w->x+30,y+20,dm_ui_translate(m->tasks[i].title),DM_COLOR(24,38,55,255));char memory[48];snprintf(memory,sizeof(memory),"%.1f KiB",dm_app_memory(m->tasks[i].window)/1024.);dm_text_raw(w->x+w->w-245,y+20,memory,DM_COLOR(24,38,55,255));dm_text(w->x+w->w-120,y+20,m->tasks[i].minimized?dm_localize("Ridotta","Minimized","Minimizada"):dm_localize("Aperta","Open","Abierta"),DM_COLOR(24,38,55,255));}const char*b[]={dm_localize("Mostra","Show","Mostrar"),dm_localize("Minimizza","Minimize","Minimizar"),dm_localize("Chiudi app","Close app","Cerrar app")};for(int i=0;i<3;i++){dm_rect(w->x+20+i*180,w->y+w->h-65,165,35,DM_COLOR(208,224,240,255));dm_text(w->x+30+i*180,w->y+w->h-41,b[i],DM_COLOR(24,38,55,255));}DmSystemInfo info;dm_system_info(&info);char s[100];snprintf(s,sizeof(s),dm_localize("%d / %d finestre | RAM libera: %.1f MiB","%d / %d windows | Free RAM: %.1f MiB","%d / %d ventanas | RAM libre: %.1f MiB"),m->count,DM_MAX_WINDOWS,info.ram_free/1048576.0);dm_text_raw(w->x+20,w->y+w->h-12,s,DM_COLOR(24,38,55,255));}
static void click(DmWindow*w,int x,int y){Manager*m=w->state;if(x>=20&&x<w->w-20&&y>=85&&y<85+m->count*28){m->selected=(y-85)/28;m->chosen=m->tasks[m->selected].window;return;}if(m->selected<0||y<w->h-65||y>=w->h-30||x<20||x>=560)return;DmWindow*t=m->chosen;if(!t||!t->used)return;int b=(x-20)/180;if(b==0)dm_focus(t);if(b==1)t->minimized=1;if(b==2){dm_close(t);return;}}
const DmApp dm_taskmanager_app={DM_API_VERSION,"taskmanager","Task Manager",sizeof(Manager),open_manager,draw,click,0,0,0,"",tick};
DM_EXPORT_APP(dm_taskmanager_app)
