#include "../wasm_app.h"
#define DM_WIDGETS_WASM
#include "../dm_widgets.h"

#define INK 0xFF182637u
#define SILVER 0xFFC0C0C0u
#define LIMIT 48
#define PATH_CAP 1024
#define ROW 27
enum {B_PREVIOUS,B_REWIND,B_PLAY,B_STOP,B_FORWARD,B_NEXT,B_PLAYLIST,B_COUNT};
static char files[LIMIT][PATH_CAP],selected_path[PATH_CAP],artist[96],track_title[96],status[128],open_directory[PATH_CAP];
static int count,selected=-1,current=-1,scroll,visible=6,height=480,playing,elapsed,position_ms,duration_ms;
static int playlist_visible,visualization=1,volume=100,muted,volume_before_mute,seek_drag,volume_drag,app_width,time_label_y;
static DmWidgetRect seek_rect,volume_rect,button_rect[B_COUNT];

static void copy(char*out,unsigned cap,const char*in){if(!cap)return;unsigned n=0;while(in&&in[n]&&n+1<cap){out[n]=in[n];n++;}out[n]=0;}
static unsigned length(const char*p){unsigned n=0;while(p&&p[n])n++;return n;}
static int same(const char*a,const char*b){unsigned i=0;while(a[i]&&a[i]==b[i])i++;return a[i]==b[i];}
static int same_ext(const char*a,const char*b){unsigned i=0;for(;;i++){char x=a[i],y=b[i];if(x>='A'&&x<='Z')x=(char)(x+32);if(y>='A'&&y<='Z')y=(char)(y+32);if(x!=y)return 0;if(!x)return 1;}}
static const char *base(const char*p){const char*name=p;for(unsigned i=0;p[i];i++)if(p[i]=='/'||p[i]=='\\')name=p+i+1;return name;}
static const char *ext(const char*p){const char*name=base(p),*dot=0;for(unsigned i=0;name[i];i++)if(name[i]=='.')dot=name+i;return dot?dot:"";}
static void parent_directory(char*out,unsigned cap,const char*path){copy(out,cap,"ux0:/data/desktop-mode/Desktop/");if(!path||!path[0])return;unsigned n=length(path),end=n;while(end&&path[end-1]!='/'&&path[end-1]!='\\')end--;if(end&&end<cap){for(unsigned i=0;i<end;i++)out[i]=path[i];out[end]=0;}}
static void sync_scroll(void){if(scroll<0)scroll=0;int max=count-visible;if(max<0)max=0;if(scroll>max)scroll=max;}
static int add_file(const char*p){if(!p||!p[0])return -1;for(int i=0;i<count;i++)if(same(files[i],p)){selected=i;return i;}if(count==LIMIT){copy(status,sizeof(status),"Playlist piena (massimo 48 file)");return -1;}copy(files[count],sizeof(files[count]),p);selected=count++;sync_scroll();status[0]=0;return selected;}
static void refresh_track(void){position_ms=dm_host_media_time_ms();duration_ms=dm_host_media_duration_ms();if(position_ms<0)position_ms=0;if(duration_ms<0)duration_ms=0;}
static void get_tags(void){artist[0]=track_title[0]=0;(void)dm_host_media_metadata(artist,sizeof(artist),track_title,sizeof(track_title));}
static void play(int i){if(i<0||i>=count)return;selected=current=i;copy(selected_path,sizeof(selected_path),files[i]);if(dm_host_media_open(selected_path)==0&&dm_host_media_action(DM_WASM_MEDIA_PLAY)==0){playing=1;status[0]=0;get_tags();refresh_track();}else{playing=0;copy(status,sizeof(status),"Impossibile avviare il file audio");}}
static void choose_files(void){dm_host_file_dialog_at("Aggiungi file al lettore",".wav,.mp3,.m4a,.mp4,.mid,.midi,.rmi,.aif,.aiff,.aifc,.au,.snd,.voc",0,open_directory,selected_path,sizeof(selected_path));}
static void seek_by(int delta){refresh_track();int target=position_ms+delta;if(target<0)target=0;if(duration_ms>0&&target>duration_ms)target=duration_ms;if(dm_host_media_seek_ms(target)<0)copy(status,sizeof(status),"Ricerca non supportata per questo formato");else{position_ms=target;status[0]=0;}}
static void set_volume(int v){if(v<0)v=0;if(v>100)v=100;volume=v;if(dm_host_media_set_volume(v)<0)copy(status,sizeof(status),"Volume non disponibile");else{muted=v==0;if(v)volume_before_mute=v;status[0]=0;}}
static void toggle_play(void){if(playing){dm_host_media_action(DM_WASM_MEDIA_PAUSE);playing=0;}else if(current>=0){if(dm_host_media_action(DM_WASM_MEDIA_PLAY)==0)playing=1;else play(current);}else if(selected>=0)play(selected);}
static void stop(void){dm_host_media_action(DM_WASM_MEDIA_STOP);playing=0;position_ms=0;}
static void choose_track(int i){if(i<0||i>=count)return;play(i);}
static void add_parent(const char*arg){parent_directory(open_directory,sizeof(open_directory),arg);}
uint32_t dm_app_abi_version(void){return DM_WASM_APP_ABI_VERSION;}
uint32_t dm_app_argument_buffer(void){return (uint32_t)(uintptr_t)selected_path;}
uint32_t dm_app_file_buffer(void){return (uint32_t)(uintptr_t)selected_path;}
void dm_app_file_result(uint32_t n){if(n>=sizeof(selected_path))return;selected_path[n]=0;add_parent(selected_path);int i=add_file(selected_path);if(i>=0){playlist_visible=1;copy(status,sizeof(status),"Aggiunto alla playlist: doppio clic per avviare");}}
void dm_app_init(const char*arg){count=0;selected=current=-1;scroll=0;visible=6;playing=0;elapsed=0;position_ms=duration_ms=0;height=480;artist[0]=track_title[0]=status[0]=0;playlist_visible=0;visualization=1;volume=dm_host_media_get_volume();if(volume<0||volume>100)volume=100;volume_before_mute=volume?volume:70;muted=volume==0;seek_drag=volume_drag=0;add_parent(arg);if(arg&&arg[0]){int i=add_file(arg);if(i>=0)play(i);}selected_path[0]=0;}

static void draw_fractal(int x,int y,int w,int h,int phase){if(w<1||h<1)return;const int cols=52,rows=18,cw=w/cols?w/cols:1,ch=h/rows?h/rows:1;for(int iy=0;iy<rows;iy++)for(int ix=0;ix<cols;ix++){float cr=(float)ix/cols*3.2f-2.35f,ci=(float)iy/rows*2.0f-1.0f,zr=0,zi=0;int n=0;while(zr*zr+zi*zi<4&&n<25){float t=zr*zr-zi*zi+cr;zi=2*zr*zi+ci;zr=t;n++;}unsigned r=5+(unsigned)((n*13+phase)%100),g=12+(unsigned)((n*7+phase*2)%140),b=35+(unsigned)((n*11+phase*3)%220);if(n==25)r=g=b=3;dm_host_rect(x+ix*cw,y+iy*ch,cw,ch,0xFF000000u|(b<<16)|(g<<8)|r);}}
static void file_icon(int x,int y,const char*e){uint32_t c=0xFF71869Bu;if(same_ext(e,".mp3"))c=0xFF316CC5u;else if(same_ext(e,".wav"))c=0xFF298C86u;else if(same_ext(e,".mid")||same_ext(e,".midi"))c=0xFF8654B7u;else if(same_ext(e,".rmi"))c=0xFF9859A7u;else if(same_ext(e,".m4a"))c=0xFF4493C9u;else if(same_ext(e,".mp4"))c=0xFFBE5945u;else if(same_ext(e,".aif")||same_ext(e,".aiff")||same_ext(e,".aifc"))c=0xFFAA7C36u;else if(same_ext(e,".au")||same_ext(e,".snd"))c=0xFF6D8E43u;else if(same_ext(e,".voc"))c=0xFF6473B5u;dm_host_rect(x,y,21,21,0xFFFFFFFFu);dm_host_rect(x+3,y+3,15,15,c);if(same_ext(e,".mp4")){dm_host_rect(x+8,y+7,2,8,0xFFFFFFFFu);dm_host_rect(x+10,y+8,2,6,0xFFFFFFFFu);dm_host_rect(x+12,y+9,2,4,0xFFFFFFFFu);}else{dm_host_rect(x+7,y+12,4,3,0xFFFFFFFFu);dm_host_rect(x+12,y+9,4,3,0xFFFFFFFFu);dm_host_rect(x+10,y+5,2,8,0xFFFFFFFFu);dm_host_rect(x+15,y+4,2,7,0xFFFFFFFFu);dm_host_rect(x+10,y+4,7,2,0xFFFFFFFFu);}}
static int display_height(int w,int h){int max=h-113;int n=playlist_visible?h*34/100:max;if(n>max)n=max;if(n<72)n=72;if(n>w)n=w;return n;}
static void append_number(char*out,unsigned cap,unsigned*at,unsigned value,unsigned digits){char rev[12];unsigned n=0;do{rev[n++]=(char)('0'+value%10);value/=10;}while(value&&n<sizeof(rev));while(n<digits)rev[n++]='0';while(n&&*at+1<cap)out[(*at)++]=rev[--n];}
static void format_time(char*out,unsigned cap,int ms){if(!cap)return;if(ms<0)ms=0;unsigned sec=(unsigned)ms/1000,mins=sec/60,hours=mins/60,at=0;sec%=60;mins%=60;if(hours){append_number(out,cap,&at,hours,1);if(at+1<cap)out[at++]=':';append_number(out,cap,&at,mins,2);if(at+1<cap)out[at++]=':';}else{append_number(out,cap,&at,(unsigned)ms/60000,1);if(at+1<cap)out[at++]=':';}append_number(out,cap,&at,sec,2);out[at<cap?at:cap-1]=0;}
static void layout_controls(int w,int h){app_width=w;int y=h-42,x=10,size=28,gap=2;for(int i=0;i<B_COUNT;i++){button_rect[i]=(DmWidgetRect){x,y,size,30};x+=size+gap;}volume_rect=(DmWidgetRect){x+20,y+8,w-x-76,14};if(volume_rect.w<32)volume_rect.w=32;int label_width=dm_host_text_width("000:00:00");if(label_width<40)label_width=40;int left=8+label_width+10,right=w-8-label_width-10;if(right-left<24){left=48;right=w-48;}seek_rect=(DmWidgetRect){left,display_height(w,h)+33,right-left,14};time_label_y=seek_rect.y+13;}
static void draw_toolbar(int w,int h){layout_controls(w,h);dm_host_rect(0,h-47,w,47,SILVER);dmw_border((DmWidgetRect){0,h-47,w,47},0);for(int i=0;i<B_COUNT;i++){int glyph=i==B_PREVIOUS?DMW_ICON_PREVIOUS:i==B_REWIND?DMW_ICON_REWIND:i==B_PLAY?(playing?DMW_ICON_PAUSE:DMW_ICON_PLAY):i==B_STOP?DMW_ICON_STOP:i==B_FORWARD?DMW_ICON_FORWARD:i==B_NEXT?DMW_ICON_NEXT:DMW_ICON_PLAYLIST;dmw_icon_button(button_rect[i],glyph,0,i==B_PLAYLIST&&playlist_visible);}int vol=muted?0:volume;dmw_icon_button((DmWidgetRect){button_rect[B_COUNT-1].x+7,h-43,20,24},muted?DMW_ICON_MUTE:DMW_ICON_SPEAKER,0,0);dmw_trackbar(volume_rect,vol,0,100,0);}
void dm_app_draw(int32_t w,int32_t h){height=h;dm_host_rect(0,0,w,h,SILVER);int dh=display_height(w,h),dx=8,dy=7,dw=w-16;if(dw<1)dw=1;dm_host_rect(dx,dy,dw,dh,0xFF000000u);if(visualization)draw_fractal(dx+2,dy+2,dw-4,dh-4,playing?(elapsed/80)%255:0);if(current>=0){dm_host_rect(dx+3,dy+dh-27,dw-6,24,0x99000000u);const char*title=track_title[0]?track_title:base(files[current]);dm_host_text(dx+10,dy+dh-10,title,0xFFFFFFFFu);if(artist[0]&&h>=250)dm_host_text(dx+10,dy+dh-29,artist,0xFFDBE6F2u);}else{dm_host_text(w/2-56,dy+dh/2,"Media Player",0xFFE0E0E0u);}
 dmw_border((DmWidgetRect){dx,dy,dw,dh},1);layout_controls(w,h);refresh_track();char now[24],total[24];format_time(now,sizeof(now),position_ms);format_time(total,sizeof(total),duration_ms);int seek_value=duration_ms>0?(int)((int64_t)position_ms*1000/duration_ms):0;dmw_trackbar(seek_rect,seek_value,0,1000,0);dm_host_text(8,time_label_y,now,INK);int total_width=dm_host_text_width(total);dm_host_text(w-8-total_width,time_label_y,total,INK);
 if(playlist_visible){int top=seek_rect.y+20,bottom=h-52;visible=(bottom-top)/ROW;if(visible<1)visible=1;sync_scroll();dm_host_rect(8,top,w-16,bottom-top,0xFFF8F8F8u);dmw_border((DmWidgetRect){8,top,w-16,bottom-top},1);for(int row=0;row<visible&&scroll+row<count;row++){int i=scroll+row,y=top+row*ROW,is_selected=i==selected||i==current;uint32_t row_color=is_selected?dmw_color(0,0,128):(row&1)?dmw_color(255,255,255):dmw_color(240,240,240);dm_host_rect(10,y,w-28,ROW,row_color);DmWidgetColumn col={"",w-58};const char*cells[]={base(files[i])};dmw_listview_row((DmWidgetRect){35,y,w-53,ROW},&col,cells,1,is_selected,i);file_icon(13,y+3,ext(files[i]));}if(count>visible)dm_host_scrollbar_draw(w-20,top,bottom-top,6,1,count*ROW,visible*ROW,scroll*ROW);}
 draw_toolbar(w,h);if(status[0])dm_host_text(10,h-52,status,0xFF8A2020u);}

static void previous_track(void){if(count>0)play((current>0?current:count)-1);}
static void next_track(void){if(count>0)play((current+1)%count);}
static void activate_button(int i){if(i==B_PREVIOUS)previous_track();else if(i==B_REWIND)seek_by(-10000);else if(i==B_PLAY)toggle_play();else if(i==B_STOP)stop();else if(i==B_FORWARD)seek_by(10000);else if(i==B_NEXT)next_track();else if(i==B_PLAYLIST)playlist_visible=!playlist_visible;}
void dm_app_click(int32_t x,int32_t y,uint32_t buttons){if(!buttons)return;for(int i=0;i<B_COUNT;i++)if(dmw_icon_button_click(button_rect[i],x,y,0)){activate_button(i);return;}if(dmw_trackbar_click(seek_rect,x,y,0,1000,0,&position_ms)){if(duration_ms>0){position_ms=(int)((int64_t)position_ms*duration_ms/1000);dm_host_media_seek_ms(position_ms);seek_drag=1;}return;}if(dmw_trackbar_click(volume_rect,x,y,0,100,0,&volume)){muted=volume==0;if(volume)volume_before_mute=volume;dm_host_media_set_volume(volume);volume_drag=1;return;}if(y>=height-43&&y<height-8){int mx=button_rect[B_COUNT-1].x+7;if(x>=mx&&x<mx+20){if(muted||volume==0){set_volume(volume_before_mute?volume_before_mute:70);muted=0;}else{volume_before_mute=volume;set_volume(0);muted=1;}return;}}if(playlist_visible){int top=seek_rect.y+20,bottom=height-52;if(y>=top&&y<bottom){int i=scroll+(y-top)/ROW;if(i>=0&&i<count)choose_track(i);return;}}}
void dm_app_key(int32_t key){if(key==DM_WASM_KEY_UP){scroll--;sync_scroll();}else if(key==DM_WASM_KEY_DOWN){scroll++;sync_scroll();}else if(key==DM_WASM_KEY_LEFT)seek_by(-5000);else if(key==DM_WASM_KEY_RIGHT)seek_by(5000);else if(key==DM_WASM_KEY_ENTER)toggle_play();}
void dm_app_tick(uint32_t ms){elapsed+=(int)ms;if(elapsed>0x3fffffff)elapsed=0;int32_t x=0,y=0,held=0;int focused=dm_host_pointer_state(&x,&y,&held);if(seek_drag||volume_drag){if(!focused||!held){seek_drag=volume_drag=0;}else if(seek_drag&&duration_ms>0){int value=duration_ms>0?(int)((int64_t)position_ms*1000/duration_ms):0;dmw_trackbar_click(seek_rect,x,y,0,1000,0,&value);position_ms=(int)((int64_t)value*duration_ms/1000);dm_host_media_seek_ms(position_ms);}else if(volume_drag){int value=volume;dmw_trackbar_click(volume_rect,x,y,0,100,0,&value);if(value!=volume)set_volume(value);}}refresh_track();playing=dm_host_media_status()==1;}
void dm_app_menu(int32_t command){if(command==DM_WASM_MENU_OPEN)choose_files();else if(command==DM_WASM_MENU_MEDIA_TOGGLE_PLAY)toggle_play();else if(command==DM_WASM_MENU_MEDIA_STOP)stop();else if(command==DM_WASM_MENU_MEDIA_BACK)seek_by(-10000);else if(command==DM_WASM_MENU_MEDIA_FORWARD)seek_by(10000);else if(command==DM_WASM_MENU_PREVIOUS)previous_track();else if(command==DM_WASM_MENU_NEXT)next_track();else if(command==DM_WASM_MENU_MEDIA_PLAYLIST)playlist_visible=!playlist_visible;else if(command==DM_WASM_MENU_MEDIA_VISUALIZATION)visualization=!visualization;else if(command==DM_WASM_MENU_EXIT)stop();}
void dm_app_close(void){dm_host_media_action(DM_WASM_MEDIA_STOP);}
