#include "../wasm_app.h"
#define DM_WIDGETS_WASM
#include "../dm_widgets.h"

#define MAX_PAINT_W 1024
#define MAX_PAINT_H 768
#define MAX_PAINT_PIXELS (MAX_PAINT_W * MAX_PAINT_H)
#define PAINT_W canvas_w
#define PAINT_H canvas_h
#define PAINT_PIXELS (PAINT_W * PAINT_H)
#define TOOL_COUNT 16
#define POINT_LIMIT 32
#define BMP_CAP (4u * 1024u * 1024u)
#define PALETTE_COUNT 28

enum {TOOL_FREE_SELECT,TOOL_RECT_SELECT,TOOL_ERASER,TOOL_FILL,TOOL_PICKER,TOOL_ZOOM,TOOL_PENCIL,TOOL_BRUSH,TOOL_AIRBRUSH,TOOL_TEXT,TOOL_LINE,TOOL_CURVE,TOOL_RECT,TOOL_POLYGON,TOOL_ELLIPSE,TOOL_ROUNDRECT};
static uint32_t pixels[MAX_PAINT_PIXELS],undo[MAX_PAINT_PIXELS],fill_queue[MAX_PAINT_PIXELS],selection_clipboard[MAX_PAINT_PIXELS];
static unsigned char bmp_data[BMP_CAP];
static int canvas_w=480,canvas_h=300,canvas_resize_drag,resize_prompt;
static int resize_start_w,resize_start_h,resize_start_draw_w,resize_start_draw_h;
static const uint32_t palette[PALETTE_COUNT]={0xFF000000u,0xFF7F0000u,0xFF007F00u,0xFF7F7F00u,0xFF00007Fu,0xFF7F007Fu,0xFF007F7Fu,0xFF7F7F7Fu,0xFFBFBFBFu,0xFFFF0000u,0xFF00FF00u,0xFFFFFF00u,0xFF0000FFu,0xFFFF00FFu,0xFF00FFFFu,0xFFFFFFFFu,0xFF804000u,0xFFFF8040u,0xFF804080u,0xFFFF80C0u,0xFF808000u,0xFFFFC000u,0xFF008080u,0xFF80FFFFu,0xFF004080u,0xFF4080FFu,0xFF808080u,0xFFC0C0C0u};
static int image,tool=TOOL_PENCIL,brush_size=1,fill_style,zoom_percent=100,fit_mode=1,dragging,has_undo,dirty,eraser_mode,open_pending,save_pending,clipboard_w,clipboard_h,paste_mode;
static int fg_index=0,bg_index=1,fg_custom_active,canvas_x,canvas_y,view_w,view_h,draw_w,draw_h,offset_x,offset_y,hbar,vbar,scroll_drag;
static uint32_t fg_custom;
static int start_x,start_y,last_x,last_y,selection_active,selection_x0,selection_y0,selection_x1,selection_y1;
static int polygon_x[POINT_LIMIT],polygon_y[POINT_LIMIT],polygon_count,curve_stage,curve_x[3],curve_y[3],text_x,text_y,text_scale=1;
static uint32_t random_seed=0x51A7u;
static char file_path[1024],saved_path[1024],input_text[256],status[96];
static const char *tool_names[TOOL_COUNT]={"Selezione libera","Selezione rettangolare","Gomma","Riempimento","Contagocce","Ingrandimento","Matita","Pennello","Aerografo","Testo","Linea","Curva","Rettangolo","Poligono","Ellisse","Rettangolo arrotondato"};
static const uint8_t font5x7[38][7]={
 {14,17,17,31,17,17,17},{30,17,17,30,17,17,30},{14,17,16,16,16,17,14},{30,17,17,17,17,17,30},{31,16,16,30,16,16,31},{31,16,16,30,16,16,16},{14,17,16,23,17,17,15},{17,17,17,31,17,17,17},{14,4,4,4,4,4,14},{7,2,2,2,18,18,12},{17,18,20,24,20,18,17},{16,16,16,16,16,16,31},{17,27,21,21,17,17,17},{17,25,21,19,17,17,17},{14,17,17,17,17,17,14},{30,17,17,30,16,16,16},{14,17,17,17,21,18,13},{30,17,17,30,20,18,17},{15,16,16,14,1,1,30},{31,4,4,4,4,4,4},{17,17,17,17,17,17,14},{17,17,17,17,17,10,4},{17,17,17,21,21,21,10},{17,17,10,4,10,17,17},{17,17,10,4,4,4,4},{31,1,2,4,8,16,31},
 {14,17,19,21,25,17,14},{4,12,4,4,4,4,14},{14,17,1,2,4,8,31},{30,1,1,14,1,1,30},{2,6,10,18,31,2,2},{31,16,16,30,1,1,30},{14,16,16,30,17,17,14},{31,1,2,4,8,8,8},{14,17,17,14,17,17,14},{14,17,17,15,1,1,14},{0,0,4,0,0,4,0},{0,0,0,31,0,0,0}
};
static uint32_t background(void);
static void set_status(const char*text){unsigned i=0;while(text&&text[i]&&i<sizeof(status)-1){status[i]=text[i];i++;}status[i]=0;}

uint32_t dm_app_abi_version(void){return DM_WASM_APP_ABI_VERSION;}
uint32_t dm_app_file_buffer(void){return (uint32_t)(uintptr_t)file_path;}
uint32_t dm_app_text_buffer(void){return (uint32_t)(uintptr_t)input_text;}
static int min_i(int a,int b){return a<b?a:b;}static int max_i(int a,int b){return a>b?a:b;}static int clamp_i(int v,int lo,int hi){return v<lo?lo:v>hi?hi:v;}
static int ensure_buffers(int count){return count>0&&count<=MAX_PAINT_PIXELS;}
static int recreate_image(void){if(image>0)dm_host_image_free(image);image=dm_host_image_create(PAINT_W,PAINT_H,pixels);return image>0;}
static int resize_canvas(int width,int height){width=clamp_i(width,1,MAX_PAINT_W);height=clamp_i(height,1,MAX_PAINT_H);if(width==PAINT_W&&height==PAINT_H)return 1;int old_w=PAINT_W,old_h=PAINT_H,old_count=PAINT_PIXELS;if(!ensure_buffers(max_i(old_count,width*height))){set_status("Memoria insufficiente per ampliare la tela");return 0;}for(int i=0;i<old_count;i++)undo[i]=pixels[i];canvas_w=width;canvas_h=height;uint32_t bg=background();for(int i=0;i<PAINT_PIXELS;i++)pixels[i]=bg;for(int y=0;y<old_h&&y<height;y++)for(int x=0;x<old_w&&x<width;x++)pixels[y*width+x]=undo[y*old_w+x];has_undo=0;selection_active=paste_mode=0;offset_x=offset_y=0;fit_mode=0;zoom_percent=100;dirty=1;if(!recreate_image()){set_status("Memoria insufficiente per la tela");return 0;}dm_host_image_update(image,pixels);return 1;}
static uint32_t le32(const unsigned char*p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
static void set_pixel(int x,int y,uint32_t c){if(x>=0&&x<PAINT_W&&y>=0&&y<PAINT_H)pixels[y*PAINT_W+x]=c;}
static void save_undo(void){for(int i=0;i<PAINT_PIXELS;i++)undo[i]=pixels[i];has_undo=1;}
static void changed(void){dirty=1;if(image>0)dm_host_image_update(image,pixels);}
static uint32_t foreground(void){return fg_custom_active?fg_custom:palette[fg_index];}
static uint32_t background(void){return palette[bg_index];}
static void dot(int x,int y){int radius=(brush_size-1)/2;uint32_t c=(tool==TOOL_ERASER||eraser_mode)?background():foreground();for(int dy=-radius;dy<=radius;dy++)for(int dx=-radius;dx<=radius;dx++)if(dx*dx+dy*dy<=radius*radius+1)set_pixel(x+dx,y+dy,c);}
static void line_pixels(int x0,int y0,int x1,int y1){int dx=x1>x0?x1-x0:x0-x1,sx=x0<x1?1:-1,dy=y1>y0?y0-y1:y1-y0,sy=y0<y1?1:-1,err=dx+dy;for(;;){dot(x0,y0);if(x0==x1&&y0==y1)break;int e2=2*err;if(e2>=dy){err+=dy;x0+=sx;}if(e2<=dx){err+=dx;y0+=sy;}}}
static void draw_rect(int x0,int y0,int x1,int y1,int rounded){int l=min_i(x0,x1),r=max_i(x0,x1),t=min_i(y0,y1),b=max_i(y0,y1);if(fill_style==1){for(int y=t;y<=b;y++)for(int x=l;x<=r;x++){if(!rounded||(x>=l+3&&x<=r-3)||(y>=t+3&&y<=b-3))set_pixel(x,y,foreground());}}else if(fill_style==2){for(int y=t;y<=b;y++)for(int x=l;x<=r;x++)if(((x+y)&3)<2)set_pixel(x,y,foreground());}else{line_pixels(l,t,r,t);line_pixels(r,t,r,b);line_pixels(r,b,l,b);line_pixels(l,b,l,t);}if(rounded&&fill_style==0){set_pixel(l,t,background());set_pixel(l+1,t,background());set_pixel(r,t,background());set_pixel(r-1,t,background());set_pixel(l,b,background());set_pixel(l+1,b,background());set_pixel(r,b,background());set_pixel(r-1,b,background());}}
static void draw_ellipse(int x0,int y0,int x1,int y1){int l=min_i(x0,x1),r=max_i(x0,x1),t=min_i(y0,y1),b=max_i(y0,y1),rx=max_i(1,(r-l)/2),ry=max_i(1,(b-t)/2),cx=(l+r)/2,cy=(t+b)/2;int64_t edge=(int64_t)rx*rx*ry*ry;for(int y=t;y<=b;y++)for(int x=l;x<=r;x++){int64_t dx=x-cx,dy=y-cy,q=dx*dx*ry*ry+dy*dy*rx*rx;if((fill_style==1&&q<=edge)||(fill_style==2&&q<=edge&&q>edge-edge/5)||(fill_style==0&&q<=edge&&q>edge-edge/ry))set_pixel(x,y,foreground());}}
static void draw_airbrush(int cx,int cy){for(int i=0;i<30;i++){random_seed=random_seed*1664525u+1013904223u;int dx=(int)(random_seed%17)-8;random_seed=random_seed*1664525u+1013904223u;int dy=(int)(random_seed%17)-8;if(dx*dx+dy*dy<=64)set_pixel(cx+dx,cy+dy,foreground());}}
static void fill_area(int sx,int sy){uint32_t target=pixels[sy*PAINT_W+sx],replacement=foreground();if(target==replacement)return;unsigned head=0,tail=0;fill_queue[tail++]=(uint32_t)(sy*PAINT_W+sx);pixels[sy*PAINT_W+sx]=replacement;while(head<tail){uint32_t p=fill_queue[head++];int x=(int)(p%PAINT_W),y=(int)(p/PAINT_W);if(x>0&&pixels[p-1]==target){pixels[p-1]=replacement;fill_queue[tail++]=p-1;}if(x+1<PAINT_W&&pixels[p+1]==target){pixels[p+1]=replacement;fill_queue[tail++]=p+1;}if(y>0&&pixels[p-PAINT_W]==target){pixels[p-PAINT_W]=replacement;fill_queue[tail++]=p-PAINT_W;}if(y+1<PAINT_H&&pixels[p+PAINT_W]==target){pixels[p+PAINT_W]=replacement;fill_queue[tail++]=p+PAINT_W;}}changed();}
static int font_index(char c){if(c>='a'&&c<='z')c=(char)(c-'a'+'A');if(c>='A'&&c<='Z')return c-'A';if(c>='0'&&c<='9')return 26+c-'0';if(c=='.')return 36;if(c=='-')return 37;return -1;}
static void draw_text_pixels(int x,int y,const char*text){int cursor=x,line=x;for(int i=0;text[i];i++){if(text[i]=='\n'||cursor+6*text_scale>PAINT_W){cursor=line;y+=8*text_scale;if(text[i]=='\n')continue;}if(y+7*text_scale>PAINT_H)break;int gi=font_index(text[i]);if(gi>=0){for(int yy=0;yy<7;yy++)for(int xx=0;xx<5;xx++)if(font5x7[gi][yy]&(1u<<(4-xx)))for(int sy=0;sy<text_scale;sy++)for(int sx=0;sx<text_scale;sx++)set_pixel(cursor+xx*text_scale+sx,y+yy*text_scale+sy,foreground());}cursor+=6*text_scale;}changed();}
static void draw_polygon(void){if(polygon_count<2)return;for(int i=1;i<polygon_count;i++)line_pixels(polygon_x[i-1],polygon_y[i-1],polygon_x[i],polygon_y[i]);line_pixels(polygon_x[polygon_count-1],polygon_y[polygon_count-1],polygon_x[0],polygon_y[0]);changed();polygon_count=0;}
static void selection_copy(int cut){if(selection_active){clipboard_w=selection_x1-selection_x0+1;clipboard_h=selection_y1-selection_y0+1;}else{selection_x0=selection_y0=0;selection_x1=PAINT_W-1;selection_y1=PAINT_H-1;clipboard_w=PAINT_W;clipboard_h=PAINT_H;}if(clipboard_w<1||clipboard_h<1)return;for(int y=0;y<clipboard_h;y++)for(int x=0;x<clipboard_w;x++){int at=y*clipboard_w+x;selection_clipboard[at]=pixels[(selection_y0+y)*PAINT_W+selection_x0+x];if(cut)pixels[(selection_y0+y)*PAINT_W+selection_x0+x]=background();}if(cut){changed();selection_active=0;}paste_mode=0;}
static void paste_at(int x,int y){if(!clipboard_w||!clipboard_h)return;save_undo();for(int py=0;py<clipboard_h;py++)for(int px=0;px<clipboard_w;px++)if(x+px<PAINT_W&&y+py<PAINT_H)set_pixel(x+px,y+py,selection_clipboard[py*clipboard_w+px]);selection_x0=x;selection_y0=y;selection_x1=min_i(PAINT_W-1,x+clipboard_w-1);selection_y1=min_i(PAINT_H-1,y+clipboard_h-1);selection_active=1;paste_mode=0;changed();}
static void apply_shape(void){if(tool==TOOL_LINE)line_pixels(start_x,start_y,last_x,last_y);else if(tool==TOOL_RECT)draw_rect(start_x,start_y,last_x,last_y,0);else if(tool==TOOL_ROUNDRECT)draw_rect(start_x,start_y,last_x,last_y,1);else if(tool==TOOL_ELLIPSE)draw_ellipse(start_x,start_y,last_x,last_y);if(tool==TOOL_LINE||tool==TOOL_RECT||tool==TOOL_ROUNDRECT||tool==TOOL_ELLIPSE)changed();}
static void draw_ui_line(int x0,int y0,int x1,int y1,uint32_t color){int dx=x1>x0?x1-x0:x0-x1,sx=x0<x1?1:-1,dy=y1>y0?y0-y1:y1-y0,sy=y0<y1?1:-1,err=dx+dy;for(;;){dm_host_rect(x0,y0,1,1,color);if(x0==x1&&y0==y1)break;int e=2*err;if(e>=dy){err+=dy;x0+=sx;}if(e<=dx){err+=dx;y0+=sy;}}}
static void icon_draw(int x,int y,int id){uint32_t ink=0xFF202020u,accent=0xFF2B71B8u;dm_host_rect(x,y,20,20,0xFFF8F8F8u);dmw_border((DmWidgetRect){x,y,20,20},tool==id);int a=x+2,b=y+2;
 switch(id){case TOOL_FREE_SELECT:for(int i=0;i<12;i+=2){dm_host_rect(a+3+i,b+2,1,1,ink);dm_host_rect(a+14,b+3+i,1,1,ink);dm_host_rect(a+3+i,b+14,1,1,ink);dm_host_rect(a+2,b+3+i,1,1,ink);}break;
 case TOOL_RECT_SELECT:for(int i=0;i<12;i+=2){dm_host_rect(a+3+i,b+3,1,1,ink);dm_host_rect(a+3+i,b+14,1,1,ink);dm_host_rect(a+3,b+3+i,1,1,ink);dm_host_rect(a+14,b+3+i,1,1,ink);}break;
 case TOOL_ERASER:dm_host_rect(a+4,b+4,9,7,0xFFFFD8E5u);draw_ui_line(a+4,b+11,a+10,b+16,ink);draw_ui_line(a+13,b+5,a+9,b+11,ink);break;
 case TOOL_FILL:dm_host_rect(a+6,b+4,8,8,0xFFE8D8A0u);draw_ui_line(a+5,b+5,a+12,b+12,ink);draw_ui_line(a+5,b+5,a+10,b+3,ink);dm_host_rect(a+14,b+12,2,3,0xFF2B71B8u);break;
 case TOOL_PICKER:draw_ui_line(a+4,b+14,a+13,b+5,ink);dm_host_rect(a+12,b+3,4,4,accent);dm_host_rect(a+3,b+13,4,3,0xFFDFB56Au);break;
 case TOOL_ZOOM:dm_host_rect(a+4,b+3,8,8,ink);dm_host_rect(a+5,b+4,6,6,0xFFFFFFFFu);draw_ui_line(a+11,b+11,a+16,b+16,ink);break;
 case TOOL_PENCIL:draw_ui_line(a+4,b+15,a+14,b+4,ink);draw_ui_line(a+3,b+16,a+5,b+15,0xFFB69A72u);break;
 case TOOL_BRUSH:draw_ui_line(a+5,b+15,a+11,b+8,0xFF8B623A);dm_host_rect(a+10,b+3,5,6,accent);dm_host_rect(a+9,b+8,6,3,ink);break;
 case TOOL_AIRBRUSH:dm_host_rect(a+7,b+4,7,9,0xFF76889Au);dm_host_rect(a+5,b+13,11,2,ink);dm_host_rect(a+3,b+16,1,1,accent);dm_host_rect(a+7,b+16,1,1,accent);dm_host_rect(a+12,b+16,1,1,accent);break;
 case TOOL_TEXT:dm_host_text(x+4,y+16,"A",ink);break;
 case TOOL_LINE:draw_ui_line(a+3,b+15,a+15,b+3,ink);break;
 case TOOL_CURVE:draw_ui_line(a+3,b+14,a+7,b+10,ink);draw_ui_line(a+7,b+10,a+10,b+13,ink);draw_ui_line(a+10,b+13,a+15,b+4,ink);break;
 case TOOL_RECT:dm_host_rect(a+3,b+4,13,10,ink);dm_host_rect(a+4,b+5,11,8,0xFFF8F8F8u);break;
 case TOOL_POLYGON:draw_ui_line(a+3,b+14,a+7,b+4,ink);draw_ui_line(a+7,b+4,a+15,b+7,ink);draw_ui_line(a+15,b+7,a+13,b+15,ink);draw_ui_line(a+13,b+15,a+3,b+14,ink);break;
 case TOOL_ELLIPSE:dm_host_rect(a+3,b+5,13,8,ink);dm_host_rect(a+4,b+4,11,10,0xFFF8F8F8u);dm_host_rect(a+6,b+3,7,12,0xFFF8F8F8u);break;
 default:dm_host_rect(a+3,b+4,13,11,ink);dm_host_rect(a+5,b+3,9,13,0xFFF8F8F8u);dm_host_rect(a+6,b+4,7,9,ink);dm_host_rect(a+7,b+5,5,7,0xFFF8F8F8u);break;}}
static void layout(int width,int height){canvas_x=54;canvas_y=4;view_w=width-canvas_x-10;view_h=height-canvas_y-28;if(view_w<1)view_w=1;if(view_h<1)view_h=1;int scale=100;if(fit_mode){int sx=view_w*100/PAINT_W,sy=view_h*100/PAINT_H;scale=sx<sy?sx:sy;if(scale>100)scale=100;if(scale<10)scale=10;}else scale=zoom_percent;draw_w=PAINT_W*scale/100;draw_h=PAINT_H*scale/100;hbar=vbar=0;for(int i=0;i<3;i++){int aw=width-canvas_x-10-(vbar?12:0),ah=height-canvas_y-28-(hbar?12:0);if(aw<1)aw=1;if(ah<1)ah=1;view_w=aw;view_h=ah;hbar=draw_w>view_w;vbar=draw_h>view_h;}offset_x=clamp_i(offset_x,0,max_i(0,draw_w-view_w));offset_y=clamp_i(offset_y,0,max_i(0,draw_h-view_h));}
static DmWidgetRect horizontal_scroll_hit(void){return (DmWidgetRect){canvas_x,canvas_y+view_h-2,view_w,16};}
static void remember_path(const char*path){unsigned i=0;while(path[i]&&i<sizeof(saved_path)-1){saved_path[i]=path[i];i++;}saved_path[i]=0;}
static void load_bmp(const char*path){int32_t size=dm_host_fs_read(path,(char*)bmp_data,BMP_CAP);if(size<54||bmp_data[0]!='B'||bmp_data[1]!='M'){set_status("BMP non valido o troppo grande");return;}uint32_t off=le32(bmp_data+10),dib=le32(bmp_data+14),width=le32(bmp_data+18),raw_height=le32(bmp_data+22),compression=le32(bmp_data+30);int top_down=(int32_t)raw_height<0;uint32_t height=top_down?0u-raw_height:raw_height;unsigned bits=bmp_data[28]|((unsigned)bmp_data[29]<<8);if(dib<40||!width||!height||width>100000||height>100000||(bits!=24&&bits!=32)||compression||off>=(uint32_t)size){set_status("Formato BMP non supportato");return;}uint64_t stride=((uint64_t)width*bits+31)/32*4;if((uint64_t)off+stride*height>(uint32_t)size){set_status("BMP incompleto");return;}unsigned out_w=width,out_h=height;if(out_w>MAX_PAINT_W||out_h>MAX_PAINT_H){double sx=(double)MAX_PAINT_W/out_w,sy=(double)MAX_PAINT_H/out_h,scale=sx<sy?sx:sy;out_w=(unsigned)(out_w*scale);out_h=(unsigned)(out_h*scale);if(!out_w)out_w=1;if(!out_h)out_h=1;}if(!resize_canvas((int)out_w,(int)out_h))return;for(unsigned y=0;y<out_h;y++){unsigned source_y=(unsigned)((uint64_t)y*height/out_h);if(!top_down)source_y=height-1-source_y;const unsigned char*row=bmp_data+off+(uint64_t)source_y*stride;for(unsigned x=0;x<out_w;x++){unsigned source_x=(unsigned)((uint64_t)x*width/out_w);const unsigned char*q=row+(uint64_t)source_x*(bits/8);pixels[y*out_w+x]=0xFF000000u|((uint32_t)q[2]<<16)|((uint32_t)q[1]<<8)|q[0];}}remember_path(path);dm_host_image_update(image,pixels);dirty=0;status[0]=0;}
static void load_raster(const char*path){int handle=dm_host_image_load(path);uint32_t width=0,height=0;if(handle<1||dm_host_image_size(handle,&width,&height)<0||!width||!height){if(handle>0)dm_host_image_free(handle);set_status("Impossibile leggere l'immagine");return;}if(width>MAX_PAINT_W||height>MAX_PAINT_H){dm_host_image_free(handle);set_status("Immagine oltre il limite tela (1024 x 768)");return;}int count=(int)(width*height);if(!ensure_buffers(count)||dm_host_image_read(handle,selection_clipboard,count*4)<count*4){dm_host_image_free(handle);set_status("Memoria insufficiente per aprire l'immagine");return;}dm_host_image_free(handle);if(!resize_canvas((int)width,(int)height))return;for(int i=0;i<count;i++)pixels[i]=selection_clipboard[i];dm_host_image_update(image,pixels);remember_path(path);dirty=0;status[0]=0;}
static int ends_with(const char*path,const char*ext){unsigned i=0;while(path[i])i++;unsigned j=0;while(ext[j])j++;if(j>i)return 0;for(unsigned k=0;k<j;k++){char a=path[i-j+k],b=ext[k];if(a>='A'&&a<='Z')a=(char)(a+32);if(b>='A'&&b<='Z')b=(char)(b+32);if(a!=b)return 0;}return 1;}
static void put_le32(unsigned char*p,uint32_t n){p[0]=(unsigned char)n;p[1]=(unsigned char)(n>>8);p[2]=(unsigned char)(n>>16);p[3]=(unsigned char)(n>>24);}
static int save_bmp(const char*path){uint32_t stride=((PAINT_W*24u+31u)/32u)*4u,size=54u+stride*PAINT_H;if(size>BMP_CAP)return -1;for(unsigned i=0;i<size;i++)bmp_data[i]=0;bmp_data[0]='B';bmp_data[1]='M';put_le32(bmp_data+2,size);put_le32(bmp_data+10,54);put_le32(bmp_data+14,40);put_le32(bmp_data+18,PAINT_W);put_le32(bmp_data+22,PAINT_H);bmp_data[26]=1;bmp_data[28]=24;put_le32(bmp_data+34,stride*PAINT_H);for(int y=0;y<PAINT_H;y++)for(int x=0;x<PAINT_W;x++){uint32_t c=pixels[y*PAINT_W+x];unsigned char*q=bmp_data+54+(PAINT_H-1-y)*stride+x*3;q[0]=(unsigned char)c;q[1]=(unsigned char)(c>>8);q[2]=(unsigned char)(c>>16);}return dm_host_fs_write(path,(char*)bmp_data,(int32_t)size,0);}
static void save_to(const char*path){int result=ends_with(path,".bmp")?save_bmp(path):dm_host_image_save_png(path,PAINT_W,PAINT_H,pixels,0);if(result>=0){unsigned i=0;while(path[i]&&i<sizeof(saved_path)-1){saved_path[i]=path[i];i++;}saved_path[i]=0;dirty=0;status[0]=0;}else{const char*m="Salvataggio non riuscito";unsigned i=0;while(m[i]&&i<sizeof(status)-1){status[i]=m[i];i++;}status[i]=0;}}
static void save(void){if(saved_path[0])save_to(saved_path);else{save_pending=1;dm_host_file_dialog("Paint - Salva immagine",".png,.bmp",1,file_path,sizeof(file_path));}}
static void open_image(void){open_pending=1;dm_host_file_dialog("Paint - Apri immagine",".bmp,.png,.jpg,.jpeg",0,file_path,sizeof(file_path));}
static void clear_canvas(void){save_undo();for(int i=0;i<PAINT_PIXELS;i++)pixels[i]=background();saved_path[0]=0;dirty=1;changed();status[0]=0;selection_active=0;polygon_count=curve_stage=0;}
void dm_app_init(const char*argument){(void)argument;canvas_w=480;canvas_h=300;if(!ensure_buffers(PAINT_PIXELS)){set_status("Memoria insufficiente per Paint");return;}for(int i=0;i<PAINT_PIXELS;i++)pixels[i]=0xFFFFFFFFu;image=dm_host_image_create(PAINT_W,PAINT_H,pixels);tool=TOOL_PENCIL;brush_size=1;fill_style=0;zoom_percent=100;fit_mode=1;offset_x=offset_y=0;dirty=dragging=has_undo=eraser_mode=selection_active=polygon_count=curve_stage=fg_custom_active=0;canvas_resize_drag=resize_prompt=0;fg_index=0;bg_index=1;clipboard_w=clipboard_h=paste_mode=0;file_path[0]=saved_path[0]=input_text[0]=status[0]=0;}
void dm_app_file_result(uint32_t length){if(length>=sizeof(file_path))return;file_path[length]=0;if(open_pending){open_pending=0;if(ends_with(file_path,".bmp"))load_bmp(file_path);else load_raster(file_path);}else if(save_pending){save_pending=0;save_to(file_path);}}
static void canvas_point(int x,int y,int*cx,int*cy){*cx=clamp_i((x-canvas_x+offset_x)*PAINT_W/draw_w,0,PAINT_W-1);*cy=clamp_i((y-canvas_y+offset_y)*PAINT_H/draw_h,0,PAINT_H-1);}
static void render_preview(void){if(!dragging||tool==TOOL_PENCIL||tool==TOOL_BRUSH||tool==TOOL_ERASER||tool==TOOL_AIRBRUSH)return;int x0=canvas_x+start_x*draw_w/PAINT_W-offset_x,y0=canvas_y+start_y*draw_h/PAINT_H-offset_y,x1=canvas_x+last_x*draw_w/PAINT_W-offset_x,y1=canvas_y+last_y*draw_h/PAINT_H-offset_y;uint32_t c=0xFF202020u;if(tool==TOOL_LINE)draw_ui_line(x0,y0,x1,y1,c);else if(tool==TOOL_ELLIPSE){int l=min_i(x0,x1),r=max_i(x0,x1),t=min_i(y0,y1),b=max_i(y0,y1);for(int i=0;i<=24;i++){int px=l+(r-l)*i/24,py=t+(b-t)*i/24;draw_ui_line(px,t+(b-t)/2,px,py,c);}}else{draw_ui_line(x0,y0,x1,y0,c);draw_ui_line(x1,y0,x1,y1,c);draw_ui_line(x1,y1,x0,y1,c);draw_ui_line(x0,y1,x0,y0,c);}}
void dm_app_draw(int32_t width,int32_t height){layout(width,height);dm_host_rect(0,0,width,height,0xFFC6C6C6u);
 for(int i=0;i<TOOL_COUNT;i++)icon_draw(4+(i%2)*22,4+(i/2)*21,i);
 dm_host_rect(5,173,18,18,foreground());dmw_border((DmWidgetRect){5,173,18,18},0);dm_host_rect(17,182,18,18,background());dmw_border((DmWidgetRect){17,182,18,18},0);
 for(int i=0;i<PALETTE_COUNT;i++){int x=4+(i%4)*11,y=204+(i/4)*11;dm_host_rect(x,y,10,10,palette[i]);dmw_border((DmWidgetRect){x,y,10,10},0);if(i==fg_index)dm_host_rect(x+1,y+1,2,2,0xFFFFFFFFu);}
 dm_host_rect(canvas_x,canvas_y,view_w,view_h,0xFFC6C6C6u);if(image>0)dm_host_image_draw_clipped(image,canvas_x-offset_x,canvas_y-offset_y,draw_w,draw_h,canvas_x,canvas_y,view_w,view_h);render_preview();if(selection_active){int x0=canvas_x+selection_x0*draw_w/PAINT_W-offset_x,y0=canvas_y+selection_y0*draw_h/PAINT_H-offset_y,x1=canvas_x+selection_x1*draw_w/PAINT_W-offset_x,y1=canvas_y+selection_y1*draw_h/PAINT_H-offset_y;for(int x=x0;x<=x1;x+=4){dm_host_rect(x,y0,2,1,0xFF202020u);dm_host_rect(x,y1,2,1,0xFF202020u);}for(int y=y0;y<=y1;y+=4){dm_host_rect(x0,y,1,2,0xFF202020u);dm_host_rect(x1,y,1,2,0xFF202020u);}}
 if(!hbar&&!vbar&&draw_w<=view_w&&draw_h<=view_h){int gx=canvas_x+draw_w-8,gy=canvas_y+draw_h-8;dm_host_rect(gx,gy,8,8,0xFFC6C6C6u);dm_host_rect(gx+2,gy+5,5,1,0xFF777777u);dm_host_rect(gx+5,gy+2,1,4,0xFF777777u);}
 if(hbar)dm_host_scrollbar_draw(canvas_x,canvas_y+view_h+2,view_w,10,0,draw_w,view_w,offset_x);if(vbar)dm_host_scrollbar_draw(canvas_x+view_w+2,canvas_y,10,view_h,1,draw_h,view_h,offset_y);if(hbar&&vbar)dm_host_rect(canvas_x+view_w+2,canvas_y+view_h+2,10,10,0xFFC6C6C6u);
 dm_host_text(5,height-7,tool_names[tool],0xFF202020u);if(status[0])dm_host_text(150,height-7,status,0xFF8A2020u);else if(tool==TOOL_POLYGON&&polygon_count)dm_host_text(150,height-7,"Invio chiude il poligono",0xFF202020u);else if(tool==TOOL_CURVE&&curve_stage)dm_host_text(150,height-7,"Clicca il punto di controllo",0xFF202020u);}
static void choose_tool(int id){tool=clamp_i(id,0,TOOL_COUNT-1);polygon_count=curve_stage=0;eraser_mode=tool==TOOL_ERASER;}
static void undo_action(void){if(!has_undo)return;for(int i=0;i<PAINT_PIXELS;i++){uint32_t c=pixels[i];pixels[i]=undo[i];undo[i]=c;}dirty=1;changed();}
void dm_app_click(int32_t x,int32_t y,uint32_t buttons){if(!buttons)return;
 if(x>=4&&x<48&&y>=4&&y<172){int col=(x-4)/22,row=(y-4)/21,id=row*2+col;if(col<2&&row<8){choose_tool(id);return;}}
 if(x>=5&&x<35&&y>=173&&y<201){if(fg_custom_active){fg_custom=background();fg_custom_active=0;fg_index=bg_index;bg_index=1;}else{int t=fg_index;fg_index=bg_index;bg_index=t;}return;}
 if(x>=4&&x<48&&y>=204&&y<282){int col=(x-4)/11,row=(y-204)/11,index=row*4+col;if(index>=0&&index<PALETTE_COUNT){if(buttons&2)bg_index=index;else{fg_index=index;fg_custom_active=0;}eraser_mode=0;}return;}
 if(hbar&&dmw_scrollbar_click(horizontal_scroll_hit(),x,y,draw_w,view_w,&offset_x)){scroll_drag=1;return;}if(vbar&&dmw_scrollbar_click((DmWidgetRect){canvas_x+view_w+2,canvas_y,10,view_h},x,y,draw_h,view_h,&offset_y)){scroll_drag=2;return;}
 if(!hbar&&!vbar&&draw_w<=view_w&&draw_h<=view_h&&x>=canvas_x+draw_w-10&&x<canvas_x+draw_w&&y>=canvas_y+draw_h-10&&y<canvas_y+draw_h){canvas_resize_drag=1;resize_start_w=PAINT_W;resize_start_h=PAINT_H;resize_start_draw_w=draw_w;resize_start_draw_h=draw_h;return;}
 if(x<canvas_x||x>=canvas_x+view_w||y<canvas_y||y>=canvas_y+view_h)return;int cx,cy;canvas_point(x,y,&cx,&cy);if(paste_mode){paste_at(cx,cy);return;}
 if(tool==TOOL_ZOOM){fit_mode=0;zoom_percent=zoom_percent>=400?50:zoom_percent*2;offset_x=offset_y=0;return;}if(tool==TOOL_PICKER){fg_custom=pixels[cy*PAINT_W+cx];fg_custom_active=1;return;}if(tool==TOOL_FILL){save_undo();fill_area(cx,cy);return;}if(tool==TOOL_TEXT){text_x=cx;text_y=cy;dm_host_text_prompt("Paint - inserisci testo","",input_text,sizeof(input_text));return;}
 if(tool==TOOL_POLYGON){if(polygon_count==0)save_undo();if(polygon_count<POINT_LIMIT){polygon_x[polygon_count]=cx;polygon_y[polygon_count++]=cy;}return;}if(tool==TOOL_CURVE){if(curve_stage==0){save_undo();curve_x[0]=cx;curve_y[0]=cy;curve_stage=1;}else if(curve_stage==1){curve_x[2]=cx;curve_y[2]=cy;curve_stage=2;}else{curve_x[1]=cx;curve_y[1]=cy;int px=curve_x[0],py=curve_y[0];for(int t=1;t<=40;t++){int u=40-t,nx=(u*u*curve_x[0]+2*u*t*curve_x[1]+t*t*curve_x[2])/1600,ny=(u*u*curve_y[0]+2*u*t*curve_y[1]+t*t*curve_y[2])/1600;line_pixels(px,py,nx,ny);px=nx;py=ny;}curve_stage=0;changed();}return;}
 save_undo();canvas_point(x,y,&start_x,&start_y);last_x=start_x;last_y=start_y;dragging=1;if(tool==TOOL_PENCIL||tool==TOOL_BRUSH||tool==TOOL_ERASER){dot(start_x,start_y);changed();}else if(tool==TOOL_AIRBRUSH){draw_airbrush(start_x,start_y);changed();}}
void dm_app_tick(uint32_t ms){(void)ms;int32_t x=0,y=0,held=0,focused=dm_host_pointer_state(&x,&y,&held);if(canvas_resize_drag){if(focused&&held)return;canvas_resize_drag=0;int nw=resize_start_w+(x-(canvas_x+resize_start_draw_w))*resize_start_w/max_i(1,resize_start_draw_w);int nh=resize_start_h+(y-(canvas_y+resize_start_draw_h))*resize_start_h/max_i(1,resize_start_draw_h);resize_canvas(clamp_i(nw,1,MAX_PAINT_W),clamp_i(nh,1,MAX_PAINT_H));return;}if(scroll_drag){if(!focused||!held)scroll_drag=0;else if(scroll_drag==1)dmw_scrollbar_click(horizontal_scroll_hit(),x,y,draw_w,view_w,&offset_x);else dmw_scrollbar_click((DmWidgetRect){canvas_x+view_w+2,canvas_y,10,view_h},x,y,draw_h,view_h,&offset_y);return;}if(!dragging)return;if(focused&&held&&x>=canvas_x&&x<canvas_x+view_w&&y>=canvas_y&&y<canvas_y+view_h){canvas_point(x,y,&last_x,&last_y);if(tool==TOOL_PENCIL||tool==TOOL_BRUSH||tool==TOOL_ERASER)line_pixels(start_x,start_y,last_x,last_y),start_x=last_x,start_y=last_y;else if(tool==TOOL_AIRBRUSH)draw_airbrush(last_x,last_y);if(tool==TOOL_PENCIL||tool==TOOL_BRUSH||tool==TOOL_ERASER||tool==TOOL_AIRBRUSH)changed();}else if(!focused||!held){if(tool==TOOL_RECT_SELECT||tool==TOOL_FREE_SELECT){selection_active=1;selection_x0=min_i(start_x,last_x);selection_y0=min_i(start_y,last_y);selection_x1=max_i(start_x,last_x);selection_y1=max_i(start_y,last_y);}else apply_shape();dragging=0;}}
void dm_app_text(uint32_t n){if(n>=sizeof(input_text))n=sizeof(input_text)-1;input_text[n]=0;if(resize_prompt){int w=0,h=0;char*p=input_text;while(*p>='0'&&*p<='9'){if(w<=MAX_PAINT_W)w=w*10+(*p-'0');p++;}if(*p=='x'||*p=='X'||*p==',')p++;while(*p>='0'&&*p<='9'){if(h<=MAX_PAINT_H)h=h*10+(*p-'0');p++;}if(w>0&&h>0&&w<=MAX_PAINT_W&&h<=MAX_PAINT_H){if(resize_canvas(w,h))set_status("Dimensione tela aggiornata");}else set_status("Usa larghezza x altezza (max 1024 x 768)");resize_prompt=0;return;}if(tool==TOOL_TEXT){save_undo();draw_text_pixels(text_x,text_y,input_text);}}
void dm_app_key(int32_t key){if(key==DM_WASM_KEY_SAVE)save();else if(key==DM_WASM_KEY_COPY)selection_copy(0);else if(key==DM_WASM_KEY_CUT)selection_copy(1);else if(key==DM_WASM_KEY_PASTE&&clipboard_w)paste_mode=1;else if(key==DM_WASM_KEY_SELECT_ALL){selection_active=1;selection_x0=selection_y0=0;selection_x1=PAINT_W-1;selection_y1=PAINT_H-1;}else if(key==DM_WASM_KEY_ENTER&&tool==TOOL_POLYGON)draw_polygon();else if(key==DM_WASM_KEY_ENTER&&tool==TOOL_CURVE)curve_stage=0;else if(key==DM_WASM_KEY_LEFT)offset_x=clamp_i(offset_x-24,0,max_i(0,draw_w-view_w));else if(key==DM_WASM_KEY_RIGHT)offset_x=clamp_i(offset_x+24,0,max_i(0,draw_w-view_w));else if(key==DM_WASM_KEY_UP)offset_y=clamp_i(offset_y-24,0,max_i(0,draw_h-view_h));else if(key==DM_WASM_KEY_DOWN)offset_y=clamp_i(offset_y+24,0,max_i(0,draw_h-view_h));else if(key==DM_WASM_KEY_DELETE)clear_canvas();}
void dm_app_menu(int32_t command){if(command==DM_WASM_MENU_NEW)clear_canvas();else if(command==DM_WASM_MENU_OPEN)open_image();else if(command==DM_WASM_MENU_SAVE)save();else if(command==DM_WASM_MENU_SAVE_AS){save_pending=1;dm_host_file_dialog("Paint - Salva immagine",".png,.bmp",1,file_path,sizeof(file_path));}else if(command==DM_WASM_MENU_UNDO)undo_action();else if(command==DM_WASM_MENU_CUT)dm_app_key(DM_WASM_KEY_CUT);else if(command==DM_WASM_MENU_COPY)dm_app_key(DM_WASM_KEY_COPY);else if(command==DM_WASM_MENU_PASTE)dm_app_key(DM_WASM_KEY_PASTE);else if(command==DM_WASM_MENU_SELECT_ALL)dm_app_key(DM_WASM_KEY_SELECT_ALL);else if(command==DM_WASM_MENU_ZOOM_IN){fit_mode=0;zoom_percent=clamp_i(zoom_percent*2,50,400);}else if(command==DM_WASM_MENU_ZOOM_OUT){fit_mode=0;zoom_percent=clamp_i(zoom_percent/2,50,400);}else if(command==DM_WASM_MENU_IMAGE_SIZE){resize_prompt=1;int n=0,w=PAINT_W,h=PAINT_H;char rev[12];do{rev[n++]=(char)('0'+w%10);w/=10;}while(w&&n<10);for(int i=0;i<n;i++)input_text[i]=rev[n-i-1];input_text[n++]='x';int m=0;do{rev[m++]=(char)('0'+h%10);h/=10;}while(h&&m<10);for(int i=0;i<m;i++)input_text[n++]=rev[m-i-1];input_text[n]=0;dm_host_text_prompt("Paint - Attributi immagine",input_text,input_text,sizeof(input_text));}else if(command==DM_WASM_MENU_CLEAR)clear_canvas();}
uint32_t dm_app_dirty(void){return dirty!=0;}
void dm_app_discard(void){dirty=0;}
void dm_app_close(void){if(image>0)dm_host_image_free(image);image=0;}
