#include "../wasm_app.h"
#define DM_WIDGETS_WASM
#include "../dm_widgets.h"

#define CARD_W 62
#define CARD_H 76
static int tab[7][52],tn[7],stock[52],sn,waste[52],wn,foundation[4][13],fn[4];
static unsigned face[7];static unsigned seed,elapsed,games;static int selected_type=-1,selected_pile=-1,selected_at=-1,view_width,view_height;
static char message[96]="Pesca dal mazzo e sposta le carte tra le colonne.";
static int rank_of(int c){return c%13+1;}static int suit_of(int c){return c/13;}static int red(int c){int s=suit_of(c);return s==1||s==2;}
static unsigned rnd(void){seed=seed*1664525u+1013904223u;return seed;}
static int number(char*out,unsigned value){char d[12];int n=0;do{d[n++]=(char)('0'+value%10);value/=10;}while(value&&n<11);for(int i=0;i<n;i++)out[i]=d[n-i-1];return n;}
static void deselect(void){selected_type=selected_pile=selected_at=-1;}
static void new_game(void){int deck[52];for(int i=0;i<52;i++)deck[i]=i;seed=elapsed^(++games*0x9e3779b9u);for(int i=51;i>0;i--){int j=rnd()%(i+1),t=deck[i];deck[i]=deck[j];deck[j]=t;}for(int c=0;c<7;c++){tn[c]=c+1;for(int i=0;i<=c;i++)tab[c][i]=deck[(c*(c+1))/2+i];face[c]=1;}int at=28;sn=24;for(int i=0;i<sn;i++)stock[i]=deck[at+i];wn=0;for(int i=0;i<4;i++)fn[i]=0;deselect();int n=0;const char*p="Partita ";while(p[n]){message[n]=p[n];n++;}n+=number(message+n,games);const char*s=" | seleziona carta e destinazione.";for(int i=0;s[i]&&n<(int)sizeof(message)-1;i++)message[n++]=s[i];message[n]=0;}
uint32_t dm_app_abi_version(void){return DM_WASM_APP_ABI_VERSION;}
void dm_app_init(const char*a){(void)a;elapsed=games=0;new_game();}
void dm_app_tick(uint32_t ms){elapsed+=ms;}
static void card(int x,int y,int id,int back,int mark){dm_host_rect(x,y,CARD_W,CARD_H,back?0xFF365B8Au:0xFFFDFDFDu);dm_host_rect(x,y,CARD_W,1,0xFF26384Du);dm_host_rect(x,y,1,CARD_H,0xFF26384Du);if(back){dm_host_rect(x+5,y+5,CARD_W-10,CARD_H-10,0xFF547DAFu);return;}static const char *ranks[]={"","A","2","3","4","5","6","7","8","9","10","J","Q","K"};static const char*suits[]={"C","D","H","S"};char text[8];int r=rank_of(id),s=suit_of(id),n=0;for(int i=0;ranks[r][i];i++)text[n++]=ranks[r][i];text[n++]=' ';text[n++]=suits[s][0];text[n]=0;dm_host_text(x+5,y+18,text,red(id)?0xFFC52222u:0xFF202A36u);if(mark)dm_host_rect(x+2,y+2,CARD_W-4,CARD_H-4,0x5597C3F6u);}
static int col_x(int c){return 14+c*86;}
void dm_app_draw(int32_t width,int32_t height){view_width=width;view_height=height;dmw_button((DmWidgetRect){12,4,120,29},"Nuova partita",0,0);card(18,44,0,sn==0,0);if(wn)card(96,44,waste[wn-1],0,selected_type==1);else dm_host_rect(96,44,CARD_W,CARD_H,0x887D8998u);for(int s=0;s<4;s++){int x=width-4*75+4+s*75;if(fn[s])card(x,44,foundation[s][fn[s]-1],0,selected_type==2&&selected_pile==s);else dm_host_rect(x,44,CARD_W,CARD_H,0x887D8998u);}
    for(int c=0;c<7;c++){int x=col_x(c);if(!tn[c])dm_host_rect(x,148,CARD_W,CARD_H,0x557D8998u);int y=148;for(int i=0;i<tn[c];i++){int isup=i>=(int)(tn[c]-face[c]);card(x,y,tab[c][i],!isup,selected_type==0&&selected_pile==c&&i>=selected_at);y+=isup?18:13;if(y>270)break;}}
    char stock_count[48];int n=0;const char*p="Stock ";while(p[n]){stock_count[n]=p[n];n++;}n+=number(stock_count+n,(unsigned)sn);p=" | Fondazioni ";for(int i=0;p[i];i++)stock_count[n++]=p[i];n+=number(stock_count+n,(unsigned)(fn[0]+fn[1]+fn[2]+fn[3]));p="/52";for(int i=0;p[i];i++)stock_count[n++]=p[i];stock_count[n]=0;dm_host_text(18,135,stock_count,DM_WASM_COLOR_TEXT);dm_host_text(14,view_height-8,message,DM_WASM_COLOR_TEXT);
}
static int valid_tableau(int moving,int c){if(!tn[c])return rank_of(moving)==13;int top=tab[c][tn[c]-1];return red(moving)!=red(top)&&rank_of(moving)+1==rank_of(top);}
static int remove_selected(int*out,int*count){if(selected_type==0){int c=selected_pile,at=selected_at;if(c<0||c>=7||at<0||at>=tn[c])return -1;int old_start=tn[c]-(int)face[c];*count=tn[c]-at;for(int i=0;i<*count;i++)out[i]=tab[c][at+i];tn[c]=at;face[c]=at>old_start?(unsigned)(at-old_start):0;return 0;}if(selected_type==1){if(!wn)return -1;out[0]=waste[--wn];*count=1;return 0;}if(selected_type==2){int s=selected_pile;if(s<0||s>=4||!fn[s])return -1;out[0]=foundation[s][--fn[s]];*count=1;return 0;}return -1;}
static void moved(void){const char*s="Mossa eseguita.";int i=0;while(s[i]){message[i]=s[i];i++;}message[i]=0;}
static void choose_tableau(int c,int at){if(tn[c]&&face[c]&&at>=tn[c]-(int)face[c]&&at<tn[c]){if(selected_type>=0&&(selected_type!=0||selected_pile!=c)){int cards[52],count=0,moving=selected_type==0?tab[selected_pile][selected_at]:selected_type==1?waste[wn-1]:foundation[selected_pile][fn[selected_pile]-1];if(valid_tableau(moving,c)&&!remove_selected(cards,&count)){for(int i=0;i<count;i++)tab[c][tn[c]++]=cards[i];face[c]=count;deselect();moved();return;}}selected_type=0;selected_pile=c;selected_at=at;return;}if(!tn[c]&&selected_type>=0){int cards[52],count=0,moving=selected_type==0?tab[selected_pile][selected_at]:selected_type==1?waste[wn-1]:foundation[selected_pile][fn[selected_pile]-1];if(valid_tableau(moving,c)&&!remove_selected(cards,&count)){for(int i=0;i<count;i++)tab[c][tn[c]++]=cards[i];face[c]=count;deselect();moved();}return;}if(tn[c]&&!face[c]){face[c]=1;return;}if(tn[c]&&face[c]){selected_type=0;selected_pile=c;selected_at=tn[c]-face[c];}}
static void move_foundation(int s){if(selected_type<0||s<0||s>=4)return;int moving=selected_type==0?tab[selected_pile][selected_at]:selected_type==1?(wn?waste[wn-1]:-1):selected_type==2&&fn[selected_pile]?foundation[selected_pile][fn[selected_pile]-1]:-1;if(moving<0||suit_of(moving)!=s)return;int r=rank_of(moving);if((r==1&&!fn[s])||(fn[s]&&rank_of(foundation[s][fn[s]-1])+1==r)){int cards[52],count=0;if(!remove_selected(cards,&count)){foundation[s][fn[s]++]=cards[0];deselect();int total=fn[0]+fn[1]+fn[2]+fn[3];if(total==52){const char*p="Hai completato il solitario!";int i=0;while(p[i]){message[i]=p[i];i++;}message[i]=0;}else{int i=0;const char*p="Mossa eseguita. Fondazioni: ";while(p[i]){message[i]=p[i];i++;}i+=number(message+i,(unsigned)total);p="/52";for(int j=0;p[j];j++)message[i++]=p[j];message[i]=0;}}}}
void dm_app_click(int32_t x,int32_t y,uint32_t b){if(!b)return;if(dmw_button_click((DmWidgetRect){12,4,120,29},x,y,0)){new_game();return;}if(y>=40&&y<125){if(x<80){if(sn){waste[wn++]=stock[--sn];deselect();}else if(wn){while(wn)stock[sn++]=waste[--wn];deselect();}return;}if(x>=view_width-4*75&&x<view_width){int s=(x-(view_width-4*75))/75;move_foundation(s);return;}if(x>=90&&x<170&&wn){selected_type=1;selected_pile=0;selected_at=0;return;}}if(y>=135&&x<14+7*86){int c=(x-14)/86;if(c<0||c>=7)return;int at=tn[c]?0:0;if(tn[c]&&face[c]){int start=tn[c]-face[c];at=start;for(int i=start;i<tn[c];i++)if(y>=148+(i-start)*18)at=i;}else if(tn[c])at=tn[c]-1;choose_tableau(c,at);}}
void dm_app_key(int32_t key){if(key==DM_WASM_KEY_ENTER||key==DM_WASM_KEY_SAVE)new_game();}
void dm_app_menu(int32_t command){if(command==DM_WASM_MENU_NEW)new_game();}
void dm_app_close(void){}
