static char chosen_path[DM_PATH_MAX];
static int chosen_replace,chosen_count;
static void test_chosen(const char*p,int replace,void*ctx) {
    (void)ctx;
    snprintf(chosen_path,sizeof(chosen_path),"%s",p);
    chosen_replace=replace;
    chosen_count++;
}
extern void desktop_test_mount(const char*);
static void dialog_job_tests(const char*root,const char*host_root) {
    char a[DM_PATH_MAX],b[DM_PATH_MAX],buffer[256];
    DmFileDialogOptions options= {
        DM_FILE_SAVE,"Test Salva",root,"saved.txt",".txt"
    };
    chosen_count=0;
    assert(dm_file_dialog(&options,test_chosen,NULL)==0);
    assert(dm_file_dialog(&options,test_chosen,NULL)<0);
    dm_file_dialog_click(750,460);
    assert(chosen_count==1&&!chosen_replace);
    assert(dm_fs_join(a,sizeof(a),root,"saved.txt")==0&&!strcmp(chosen_path,a));
    assert(dm_fs_write(chosen_path,"salvato",7,1)==0);
    assert(dm_file_dialog(&options,test_chosen,NULL)==0);
    dm_file_dialog_click(750,460);
    assert(dm_file_dialog_active()&&chosen_count==1);
    dm_file_dialog_click(360,285);
    assert(dm_file_dialog_active());
    dm_file_dialog_cancel();
    assert(chosen_count==1);
    assert(dm_file_dialog(&options,test_chosen,NULL)==0);
    dm_file_dialog_click(750,460);
    dm_file_dialog_click(560,285);
    assert(chosen_count==2&&chosen_replace);
    assert(dm_fs_write(chosen_path,"sostituito",10,0)==0);
    options.mode=DM_FILE_OPEN;
    assert(dm_file_dialog(&options,test_chosen,NULL)==0);
    dm_file_dialog_click(750,460);
    assert(chosen_count==3&&!chosen_replace&&!strcmp(chosen_path,a));
    options.filename="missing.txt";
    assert(dm_file_dialog(&options,test_chosen,NULL)==0);
    dm_file_dialog_click(750,460);
    assert(dm_file_dialog_active()&&chosen_count==3);
    dm_file_dialog_cancel();
    /* Shared picker used by a separately loaded Notepad module. */  DmWindow*note=dm_launch("notepad",NULL);
    assert(note);
    note->app->text(note,"Scelgo dove salvare");
    note->app->key(note,DM_KEY_SAVE);
    assert(dm_file_dialog_active());
    dm_file_dialog_click(260,412);
    assert(prompt.active);
    char filename[256];
    snprintf(filename,sizeof(filename),"%s.txt",strrchr(root,'/')+1);
    snprintf(prompt.text,sizeof(prompt.text),"%s",filename);
    prompt_done(1);
    dm_file_dialog_click(690,110);
    dm_file_dialog_click(750,460);
    assert(!dm_file_dialog_active());
    char desktop_file[DM_PATH_MAX];
    assert(dm_fs_join(desktop_file,sizeof(desktop_file),DESK,filename)==0);
    assert(dm_fs_read(desktop_file,buffer,sizeof(buffer))==19&&!strcmp(buffer,"Scelgo dove salvare"));
    assert(dm_close(note));
    assert(sceIoRemove(desktop_file)==0);
    assert(dm_fs_join(a,sizeof(a),root,"large.bin")==0);
    assert(dm_fs_join(b,sizeof(b),root,"large-copy.bin")==0);
    size_t size=2*1024*1024;
    char*data=malloc(size+1);
    assert(data);
    for(size_t i=0;i<size;i++)data[i]='A'+i%26;
    assert(dm_fs_write(a,data,size,1)==0);
    assert(dm_job_copy(a,b,NULL,NULL)==0);
    dm_job_tick();
    assert(dm_job_active());
    DmJobProgress progress;
    dm_job_progress(&progress);
    assert(progress.total==size&&progress.bytes<size);
    wait_job();
    assert(dm_fs_read(b,data,size+1)==(int)size);
    for(size_t i=0;i<size;i++)assert(data[i]==(char)('A'+i%26));
    free(data);
    char canceled[DM_PATH_MAX];
    assert(dm_fs_join(canceled,sizeof(canceled),root,"canceled.bin")==0);
    assert(dm_job_copy(a,canceled,NULL,NULL)==0);
    dm_job_tick();
    dm_job_cancel();
    SceIoStat stat;
    assert(sceIoGetstat(canceled,&stat)<0&&sceIoGetstat(a,&stat)>=0);
    /* Fresh private mount makes empty-trash tests safe for existing preview data. */  char host_mount[2048];
    snprintf(host_mount,sizeof(host_mount),"%s/private-ud0",host_root);
    assert(mkdir(host_mount,0777)==0);
    desktop_test_mount(host_mount);
    assert(sceIoMkdir("ud0:/data",0777)==0);
    assert(dm_fs_write("ud0:/data/removed.txt","recuperabile",12,1)==0);
    context_window=NULL;
    snprintf(context_target,sizeof(context_target),"ud0:/data/removed.txt");
    run_action(ACT_DELETE);
    assert(dm_confirm_active());
    dm_confirm_cancel();
    assert(sceIoGetstat(context_target,&stat)>=0);
    run_action(ACT_DELETE);
    dm_confirm_click(600,330);
    assert(dm_job_active());
    wait_job();
    assert(sceIoGetstat("ud0:/data/removed.txt",&stat)<0);
    Entry*trash=calloc(2048,sizeof(Entry));
    assert(trash);
    int n=read_trash(trash,2048),found=-1;
    for(int i=0;i<n;i++)if(!strncmp(trash[i].actual,"ud0:/",5)&&!strcmp(trash[i].name,"removed.txt"))found=i;
    assert(found>=0);
    assert(dm_fs_write("ud0:/data/removed.txt","nuovo",5,1)==0);
    assert(dm_job_restore(trash[found].actual,NULL,NULL)==0);
    wait_job();
    assert(dm_fs_read("ud0:/data/removed.txt",buffer,sizeof(buffer))==5&&!strcmp(buffer,"nuovo"));
    assert(sceIoGetstat(trash[found].actual,&stat)>=0);
    sceIoRemove("ud0:/data/removed.txt");
    assert(dm_job_restore(trash[found].actual,NULL,NULL)==0);
    wait_job();
    assert(dm_fs_read("ud0:/data/removed.txt",buffer,sizeof(buffer))==12&&!strcmp(buffer,"recuperabile"));
    assert(dm_job_trash("ud0:/data/removed.txt",NULL,NULL)==0);
    wait_job();
    assert(dm_job_trash("ud0:/data",NULL,NULL)<0);
    assert(dm_job_empty_trash_unit("ud0:",NULL,NULL)==0);
    assert(dm_job_active());
    wait_job();
    char files[DM_PATH_MAX],info[DM_PATH_MAX];
    assert(dm_trash_directories("ud0:",files,info)==0);
    assert(!dm_fs_is_directory(files)&&!dm_fs_is_directory(info));
    free(trash);
    desktop_test_mount("");
    assert(dm_days_in_month(2024,2)==29&&dm_days_in_month(2025,2)==28&&dm_days_in_month(2000,2)==29&&dm_days_in_month(1900,2)==28);
    assert(dm_clock_set_local("2026-02-30 12:00")<0);
    assert(dm_clock_set_local("2026-10-05 24:00")<0);
    assert(dm_clock_set_local("2026-10-05 12:30x")<0);
    assert(dm_clock_set_local("2026-10-05 12:30")==0);
    assert(dm_text_width("Risorse computer")>dm_text_width("Risorse"));
    /* Reject raw modules and wrong-platform envelopes before executing code. */  assert(dm_load_plugin("app0:/build/test-modules/fixture.so")<0);
    unsigned char header[36]= {
        0
    };
    memcpy(header,"DMAPP001",8);
    header[8]=1;
    header[12]=DM_API_VERSION;
    header[16]=4;
    assert(dm_fs_join(a,sizeof(a),root,"wrong.dmapp")==0&&dm_fs_write(a,header,sizeof(header),1)==0);
    int count=app_count;
    assert(dm_load_plugin(a)<0&&app_count==count);
    printf("PASS: shared open/save dialog, overwrite/cancel, Notepad picker, incremental large copy/cancel, trash/restore/empty, calendar validation, .dmapp format isolation\n");
}
