static void multi_device_tests(const char*root,const char*host_root){
 selection_test_mods=0;int total=desk_count+8,xs[32],ys[32];for(int i=0;i<total;i++){IconPosition*p=icon_position(i);xs[i]=p->x;ys[i]=p->y;p->x=i<2?20+i*120:800;p->y=i<2?20:380;}
 memset(desk_marks,0,sizeof(desk_marks));rubber.active=1;rubber.window=NULL;rubber.x=10;rubber.y=10;rubber.ctrl=0;px=250;py=120;update_rubber(1);assert(desk_marks[0]&&desk_marks[1]&&!desk_marks[2]);update_rubber(0);
 px=25;py=25;begin_icon(0);px+=30;py+=20;update_icon_drag(1);assert(icon_position(0)->x==50&&icon_position(1)->x==170);update_icon_drag(0);
 selection_test_mods=1;begin_icon(1);update_icon_drag(0);assert(desk_marks[0]&&!desk_marks[1]);selection_test_mods=0;
 for(int i=0;i<total;i++){IconPosition*p=icon_position(i);p->x=xs[i];p->y=ys[i];}memset(desk_marks,0,sizeof(desk_marks));selected_icon=pending_icon=-1;
 char desktop_dir[DM_PATH_MAX],drop_folder[DM_PATH_MAX],drop_a[DM_PATH_MAX],drop_b[DM_PATH_MAX],drop_target[DM_PATH_MAX],buf[32],drop_name[64],drop_a_name[64],drop_b_name[64];snprintf(drop_name,sizeof(drop_name),"drop-test-%ld",(long)getpid());snprintf(drop_a_name,sizeof(drop_a_name),"drop-a-%ld.txt",(long)getpid());snprintf(drop_b_name,sizeof(drop_b_name),"drop-b-%ld.txt",(long)getpid());assert(dm_fs_join(desktop_dir,sizeof(desktop_dir),STORE,"Desktop")==0);assert(dm_fs_join(drop_folder,sizeof(drop_folder),desktop_dir,drop_name)==0);assert(dm_fs_mkdir(drop_folder)==0);assert(dm_fs_join(drop_a,sizeof(drop_a),desktop_dir,drop_a_name)==0);assert(dm_fs_join(drop_b,sizeof(drop_b),desktop_dir,drop_b_name)==0);assert(dm_fs_write(drop_a,"a",1,1)==0&&dm_fs_write(drop_b,"b",1,1)==0);refresh_desktop();int folder_i=-1,a_i=-1,b_i=-1;for(int i=0;i<desk_count;i++){if(!strcmp(desk_entries[i].name,drop_name))folder_i=i;if(!strcmp(desk_entries[i].name,drop_a_name))a_i=i;if(!strcmp(desk_entries[i].name,drop_b_name))b_i=i;}assert(folder_i>=0&&a_i>=0&&b_i>=0);for(int i=0;i<desk_count+8;i++){IconPosition*p=icon_position(i);icon_start_x[i]=p->x;icon_start_y[i]=p->y;}desk_marks[a_i+8]=desk_marks[b_i+8]=1;pending_icon=a_i+8;icon_moved=1;px=icon_position(folder_i+8)->x+30;py=icon_position(folder_i+8)->y+30;update_icon_drag(0);assert(dm_drop_active()&&desk_marks[folder_i+8]);assert(dm_drop_click(250,230+2*43+5));wait_job();assert(dm_fs_join(drop_target,sizeof(drop_target),drop_folder,drop_a_name)==0&&dm_fs_read(drop_target,buf,sizeof(buf))==1);assert(dm_fs_join(drop_target,sizeof(drop_target),drop_folder,drop_b_name)==0&&dm_fs_read(drop_target,buf,sizeof(buf))==1);assert(sceIoRemove(drop_target)==0);assert(dm_fs_join(drop_target,sizeof(drop_target),drop_folder,drop_a_name)==0&&sceIoRemove(drop_target)==0);assert(sceIoRmdir(drop_folder)==0);refresh_desktop();memset(desk_marks,0,sizeof(desk_marks));selected_icon=pending_icon=-1;
 char directory[DM_PATH_MAX],destination[DM_PATH_MAX],path[DM_PATH_MAX],target[DM_PATH_MAX];assert(dm_fs_join(directory,sizeof(directory),root,"multi-source")==0);assert(dm_fs_mkdir(directory)==0);assert(dm_fs_join(destination,sizeof(destination),root,"multi-destination")==0);assert(dm_fs_mkdir(destination)==0);
 for(int i=0;i<4;i++){char name[32];snprintf(name,sizeof(name),"item%d.txt",i);assert(dm_fs_join(path,sizeof(path),directory,name)==0);assert(dm_fs_write(path,"item",4,1)==0);}
 DmWindow*w=dm_launch("explorer",directory);assert(w);Explorer*e=w->state;w->app->click(w,200,110);selection_test_mods=1;w->app->click(w,200,110+27);assert(e->marks[0]&&e->marks[1]);w->app->click(w,200,110+27);assert(e->marks[0]&&!e->marks[1]);selection_test_mods=2;w->app->click(w,200,110+81);assert(e->marks[1]&&e->marks[2]&&e->marks[3]);selection_test_mods=0;
 memset(e->marks,0,sizeof(e->marks));e->marks[0]=e->marks[1]=1;e->selected=0;context_window=w;run_action(ACT_COPY);assert(multi_clipboard_count==2);
 DmWindow*out=dm_launch("explorer",destination);assert(out);context_window=out;run_action(ACT_PASTE);wait_job();assert(dm_fs_join(target,sizeof(target),destination,"item0.txt")==0&&dm_fs_read(target,buf,sizeof(buf))==4);assert(dm_fs_join(target,sizeof(target),destination,"item1.txt")==0&&dm_fs_read(target,buf,sizeof(buf))==4);
 context_window=out;run_action(ACT_PASTE);wait_job();assert(dm_fs_join(target,sizeof(target),destination,"item0 - copia 1.txt")==0&&dm_fs_read(target,buf,sizeof(buf))==4);
 context_window=out;run_action(ACT_PASTE);assert(dm_job_active());dm_job_cancel();assert(!dm_job_active());assert(dm_fs_join(target,sizeof(target),destination,"item0 - copia 2.txt")==0&&dm_fs_read(target,buf,sizeof(buf))<0);
 assert(dm_close(out));dm_focus(w);px=w->x+w->w-10;py=w->y+100;click();assert(rubber.active);px=w->x+180;py=w->y+150;update_rubber(1);update_rubber(0);assert(e->marks[0]&&e->marks[1]&&!e->marks[2]);assert(dm_close(w));
 char unit[2048];snprintf(unit,sizeof(unit),"%s/multi-ud0",host_root);assert(mkdir(unit,0777)==0);desktop_test_mount(unit);assert(dm_fs_write("ud0:/a.txt","a",1,1)==0);assert(dm_fs_write("ud0:/b.txt","b",1,1)==0);
 w=dm_launch("explorer","ud0:/");assert(w);w->app->key(w,DM_KEY_SELECT_ALL);context_window=w;run_action(ACT_DELETE);assert(dm_confirm_active()&&multi_delete_count==2);dm_confirm_cancel();assert(dm_fs_read("ud0:/a.txt",buf,sizeof(buf))==1);run_action(ACT_DELETE);dm_confirm_click(600,330);wait_job();assert(dm_fs_read("ud0:/a.txt",buf,sizeof(buf))<0&&dm_fs_read("ud0:/b.txt",buf,sizeof(buf))<0);assert(dm_trash_has_items("ud0:"));assert(dm_close(w));desktop_test_mount("");
 free(multi_clipboard);multi_clipboard=NULL;multi_clipboard_count=0;file_clipboard[0]=0;context_window=NULL;selection_test_mods=-1;
 int old_volume=dm_volume_get();assert(dm_device_tray_click(743,520)&&dm_device_popup_active());dm_device_tray_click(710,400);assert(dm_volume_get()==10);dm_device_tray_click(700,450);assert(dm_volume_get()==0);dm_device_tray_click(700,450);assert(dm_volume_get()==10);assert(dm_volume_set(-1)<0&&dm_volume_set(31)<0);dm_volume_set(old_volume);dm_device_dismiss();
 assert(dm_device_tray_click(710,520));w=top_window();assert(w&&!strcmp(w->app->id,"bluetooth"));assert(dm_close(w));w=dm_launch("control",NULL);assert(w);w->app->click(w,370,260);DmWindow*b=top_window();assert(b&&!strcmp(b->app->id,"bluetooth"));assert(dm_close(b));assert(dm_close(w));
 printf("PASS: desktop marquee/group drag/Ctrl toggle, Explorer Ctrl/Shift/marquee, batch copy/collision and trash on private unit, volume slider/mute, Bluetooth tray/panel entry\n");
}
